def get_regions(left_coord_top_menu, width_top_menu, height_screen, width_screen):
    REGIONS_ON_WINDOW = {'left_mid': (left_coord_top_menu,
                                      height_screen / 5,
                                      width_top_menu / 5,
                                      height_screen / 3),
                         'center_up': (width_screen / 3,
                                       0,
                                       width_screen / 3,
                                       height_screen / 2),
                         'center_mid': (width_top_menu / 3,
                                        height_screen / 5,
                                        width_top_menu / 3,
                                        height_screen / 3),
                         'center_down': (width_top_menu / 3,
                                         height_screen / 2,
                                         width_top_menu / 3,
                                         height_screen / 2),
                         'right_mid': (left_coord_top_menu + width_top_menu - width_top_menu / 5,
                                       height_screen / 5,
                                       width_top_menu / 5,
                                       height_screen / 3),
                         'right_down': (left_coord_top_menu + width_top_menu / 2,
                                        height_screen / 2,
                                        width_top_menu / 2,
                                        height_screen / 2)
                         }

    REGIONS_ON_FULL_SCREEN = {'left_up': (0,
                                          0,
                                          width_screen / 2,
                                          height_screen / 2),
                              'left_mid': (0,
                                           height_screen / 4,
                                           width_screen / 5,
                                           height_screen / 2),
                              'left_down': (0,
                                            height_screen / 2,
                                            width_screen / 2,
                                            height_screen / 2),
                              'left_down_menu': (0,
                                                 height_screen - height_screen / 5,
                                                 width_screen / 5,
                                                 height_screen / 5),
                              'center_up': (width_screen / 3,
                                            0,
                                            width_screen / 3,
                                            height_screen / 2),
                              'center_mid': (width_screen / 3,
                                             height_screen / 3,
                                             width_screen / 3,
                                             height_screen / 3),
                              'center_down': (width_screen / 4,
                                              height_screen / 2,
                                              width_screen / 2,
                                              height_screen / 2),
                              'center_down_menu': (width_screen / 4,
                                                   height_screen - height_screen / 4,
                                                   width_screen / 2,
                                                   height_screen / 4),
                              'right_mid': (width_screen - width_screen / 5,
                                            height_screen / 6,
                                            width_screen / 5,
                                            height_screen / 6 * 4),
                              'right_down': (width_screen / 2,
                                             height_screen / 2,
                                             width_screen / 2,
                                             height_screen / 2),
                              'right_down_menu': (width_screen - width_screen / 5,
                                                  height_screen - height_screen / 5,
                                                  width_screen / 5,
                                                  height_screen / 5)
                              }
    return REGIONS_ON_WINDOW, REGIONS_ON_FULL_SCREEN